version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 3
  reviewers:
  - mcclowes
  ignore:
  - dependency-name: "@babel/node"
    versions:
    - 7.12.10
    - 7.13.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
  - dependency-name: copyfiles
    versions:
    - 2.4.1
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: marked
    versions:
    - 1.2.8
