name: Build CV

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers and dependencies
        uses: microsoft/playwright-github-action@v1

      - name: Build CV
        run: npm run build

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cv
          if-no-files-found: warn
          path: |
            mcclowes_cv.pdf
            index.html
            debug.html

